// Curated catalog of famous movies for offline/zero-config fallback
export const mockMovies = [
  {
    id: 278,
    title: "Cadena perpetua (The Shawshank Redemption)",
    original_title: "The Shawshank Redemption",
    year: 1994,
    directors: ["Frank Darabont"],
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler", "Clancy Brown"],
    genres: ["Drama", "Crimen"],
    country: "Estados Unidos",
    overview: "Dos hombres encarcelados forjan una amistad a lo largo de los años, encontrando consuelo y redención eventual a través de actos de decencia común.",
    poster_path: "https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    runtime: 142,
    awards: "7 nominaciones a los Óscar"
  },
  {
    id: 238,
    title: "El Padrino",
    original_title: "The Godfather",
    year: 1972,
    directors: ["Francis Ford Coppola"],
    cast: ["Marlon Brando", "Al Pacino", "James Caan", "Robert Duvall", "Diane Keaton"],
    genres: ["Drama", "Crimen"],
    country: "Estados Unidos",
    overview: "El patriarca envejecido de una dinastía del crimen organizado transfiere el control de su imperio clandestino a su reacio hijo.",
    poster_path: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    runtime: 175,
    awards: "3 premios Óscar incluyendo Mejor Película"
  },
  {
    id: 155,
    title: "El caballero oscuro (The Dark Knight)",
    original_title: "The Dark Knight",
    year: 2008,
    directors: ["Christopher Nolan"],
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine", "Maggie Gyllenhaal", "Gary Oldman"],
    genres: ["Acción", "Crimen", "Drama", "Suspense"],
    country: "Estados Unidos / Reino Unido",
    overview: "Cuando la amenaza conocida como el Joker causa estragos y caos en Gotham, Batman debe aceptar una de las mayores pruebas para combatir la injusticia.",
    poster_path: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    runtime: 152,
    awards: "2 premios Óscar, incluyendo Mejor Actor de Reparto (Heath Ledger)"
  },
  {
    id: 680,
    title: "Pulp Fiction",
    original_title: "Pulp Fiction",
    year: 1994,
    directors: ["Quentin Tarantino"],
    cast: ["John Travolta", "Samuel L. Jackson", "Uma Thurman", "Bruce Willis", "Harvey Keitel", "Tim Roth"],
    genres: ["Crimen", "Suspense"],
    country: "Estados Unidos",
    overview: "Las vidas de dos matones de la mafia, un boxeador, la esposa de un gángster y dos bandidos de poca monta se entrelazan en cuatro historias de violencia y redención.",
    poster_path: "https://image.tmdb.org/t/p/w500/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
    runtime: 154,
    awards: "Palma de Oro en Cannes y Óscar a Mejor Guion Original"
  },
  {
    id: 597,
    title: "Titanic",
    original_title: "Titanic",
    year: 1997,
    directors: ["James Cameron"],
    cast: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "Kathy Bates", "Bill Paxton"],
    genres: ["Drama", "Romance"],
    country: "Estados Unidos",
    overview: "Una aristócrata de diecisiete años se enamora de un bondadoso pero pobre artista a bordo del lujoso e desafortunado R.M.S. Titanic.",
    poster_path: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    runtime: 194,
    awards: "11 premios Óscar incluyendo Mejor Película y Director"
  },
  {
    id: 496243,
    title: "Parásitos (Parasite)",
    original_title: "Gisaengchung",
    year: 2019,
    directors: ["Bong Joon-ho"],
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik", "Park So-dam"],
    genres: ["Comedia", "Suspense", "Drama"],
    country: "Corea del Sur",
    overview: "Tanto Gi-taek como su familia están sin trabajo. Cuando su hijo mayor empieza a dar clases particulares en la adinerada casa de los Park, las dos familias entrelazan sus destinos con resultados impredecibles.",
    poster_path: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    runtime: 132,
    awards: "4 premios Óscar incluyendo Mejor Película (primera de habla no inglesa en la historia)"
  },
  {
    id: 157336,
    title: "Interstellar",
    original_title: "Interstellar",
    year: 2014,
    directors: ["Christopher Nolan"],
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine", "Matt Damon"],
    genres: ["Aventura", "Drama", "Ciencia ficción"],
    country: "Estados Unidos / Reino Unido",
    overview: "Un equipo de exploradores viaja a través de un agujero de gusano en el espacio en un intento por asegurar la supervivencia de la humanidad.",
    poster_path: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    runtime: 169,
    awards: "1 premio Óscar a Mejores Efectos Visuales"
  },
  {
    id: 129,
    title: "El viaje de Chihiro",
    original_title: "Sen to Chihiro no kamikakushi",
    year: 2001,
    directors: ["Hayao Miyazaki"],
    cast: ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki", "Takashi Naito"],
    genres: ["Animación", "Familia", "Fantasía"],
    country: "Japón",
    overview: "Durante el traslado de su familia a los suburbios, una niña de 10 años deambula por un mundo gobernado por dioses, brujas y espíritus, donde los humanos se convierten en bestias.",
    poster_path: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    runtime: 125,
    awards: "Premio Óscar a la Mejor Película de Animación y Oso de Oro en Berlín"
  },
  {
    id: 603,
    title: "Matrix",
    original_title: "The Matrix",
    year: 1999,
    directors: ["Lana Wachowski", "Lilly Wachowski"],
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving", "Joe Pantoliano"],
    genres: ["Acción", "Ciencia ficción"],
    country: "Estados Unidos / Australia",
    overview: "Un programador informático descubre que la realidad no es más que una simulación creada por máquinas inteligentes que se alimentan de la energía humana.",
    poster_path: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    runtime: 136,
    awards: "4 premios Óscar en categorías técnicas"
  },
  {
    id: 120,
    title: "El Señor de los Anillos: La Comunidad del Anillo",
    original_title: "The Lord of the Rings: The Fellowship of the Ring",
    year: 2001,
    directors: ["Peter Jackson"],
    cast: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Orlando Bloom", "Sean Astin"],
    genres: ["Aventura", "Fantasía", "Acción"],
    country: "Nueva Zelanda / Estados Unidos",
    overview: "Un tímido hobbit de la Comarca y ocho compañeros emprenden un viaje al Monte del Destino para destruir el poderoso Anillo Único.",
    poster_path: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    runtime: 178,
    awards: "4 premios Óscar"
  },
  {
    id: 122,
    title: "El Señor de los Anillos: El retorno del Rey",
    original_title: "The Lord of the Rings: The Return of the King",
    year: 2003,
    directors: ["Peter Jackson"],
    cast: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Orlando Bloom", "Sean Astin"],
    genres: ["Aventura", "Fantasía", "Acción"],
    country: "Nueva Zelanda / Estados Unidos",
    overview: "Las fuerzas de Sauron asedian Minas Tirith en su esfuerzo por erradicar la raza humana mientras Frodo y Sam se acercan a su objetivo final.",
    poster_path: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    runtime: 201,
    awards: "11 premios Óscar (récord histórico invicto, incluyendo Mejor Película)"
  },
  {
    id: 27205,
    title: "Origen (Inception)",
    original_title: "Inception",
    year: 2010,
    directors: ["Christopher Nolan"],
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy", "Ken Watanabe"],
    genres: ["Acción", "Ciencia ficción", "Aventura"],
    country: "Estados Unidos / Reino Unido",
    overview: "A un ladrón que roba secretos corporativos mediante el uso de la tecnología de intercambio de sueños se le ofrece la oportunidad de borrar su historial delictivo.",
    poster_path: "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
    runtime: 148,
    awards: "4 premios Óscar"
  },
  {
    id: 13,
    title: "Forrest Gump",
    original_title: "Forrest Gump",
    year: 1994,
    directors: ["Robert Zemeckis"],
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field", "Mykelti Williamson"],
    genres: ["Comedia", "Drama", "Romance"],
    country: "Estados Unidos",
    overview: "Las presidencias de Kennedy y Johnson, los eventos de Vietnam, Watergate y otras historias históricas se desarrollan a través de la perspectiva de un hombre de Alabama con un CI bajo.",
    poster_path: "https://image.tmdb.org/t/p/w500/arw2VCBveWOVZr6pxd9XTd1TdQa.jpg",
    runtime: 142,
    awards: "6 premios Óscar incluyendo Mejor Película y Actor"
  },
  {
    id: 550,
    title: "El club de la lucha (Fight Club)",
    original_title: "Fight Club",
    year: 1999,
    directors: ["David Fincher"],
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter", "Meat Loaf", "Jared Leto"],
    genres: ["Drama"],
    country: "Estados Unidos / Alemania",
    overview: "Un empleado de oficina insomne y un carismático fabricante de jabón forman un club de lucha clandestino que evoluciona hacia algo mucho más caótico.",
    poster_path: "https://image.tmdb.org/t/p/w500/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg",
    runtime: 139,
    awards: "Película de culto internacional"
  },
  {
    id: 424,
    title: "La lista de Schindler",
    original_title: "Schindler's List",
    year: 1993,
    directors: ["Steven Spielberg"],
    cast: ["Liam Neeson", "Ben Kingsley", "Ralph Fiennes", "Caroline Goodall"],
    genres: ["Drama", "Historia", "Bélica"],
    country: "Estados Unidos",
    overview: "En la Polonia ocupada por los alemanes durante la Segunda Guerra Mundial, el industrial Oskar Schindler se preocupa por su mano de obra judía tras presenciar su persecución.",
    poster_path: "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    runtime: 195,
    awards: "7 premios Óscar incluyendo Mejor Película y Director"
  },
  {
    id: 694,
    title: "El resplandor (The Shining)",
    original_title: "The Shining",
    year: 1980,
    directors: ["Stanley Kubrick"],
    cast: ["Jack Nicholson", "Shelley Duvall", "Danny Lloyd", "Scatman Crothers"],
    genres: ["Terror", "Suspense"],
    country: "Estados Unidos / Reino Unido",
    overview: "Una familia se dirige a un hotel aislado para pasar el invierno, donde una presencia siniestra influye en el padre hacia la violencia mientras su hijo psíquico ve visiones horribles.",
    poster_path: "https://image.tmdb.org/t/p/w500/b33nnKl1vvg6QiFc2F3hm93fAjF.jpg",
    runtime: 144,
    awards: "Clásico del cine de terror universal"
  },
  {
    id: 11,
    title: "Star Wars: Episodio IV - Una nueva esperanza",
    original_title: "Star Wars",
    year: 1977,
    directors: ["George Lucas"],
    cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Peter Cushing", "Alec Guinness"],
    genres: ["Aventura", "Acción", "Ciencia ficción"],
    country: "Estados Unidos",
    overview: "Luke Skywalker une sus fuerzas con un caballero Jedi, un arrogante piloto, un wookiee y dos droides para salvar la galaxia de la estación de batalla del Imperio.",
    poster_path: "https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    runtime: 121,
    awards: "6 premios Óscar"
  },
  {
    id: 807,
    title: "Seven (Se7en)",
    original_title: "Se7en",
    year: 1995,
    directors: ["David Fincher"],
    cast: ["Brad Pitt", "Morgan Freeman", "Gwyneth Paltrow", "Kevin Spacey"],
    genres: ["Crimen", "Misterio", "Suspense"],
    country: "Estados Unidos",
    overview: "Dos detectives, un veterano a punto de jubilarse y un impulsivo novato, van a la caza de un asesino en serie que utiliza los siete pecados capitales como móvil.",
    poster_path: "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg",
    runtime: 127,
    awards: "Nominada al Óscar"
  },
  {
    id: 194,
    title: "Amélie",
    original_title: "Le Fabuleux Destin d'Amélie Poulain",
    year: 2001,
    directors: ["Jean-Pierre Jeunet"],
    cast: ["Audrey Tautou", "Mathieu Kassovitz", "Rufus", "Lorella Cravotta"],
    genres: ["Comedia", "Romance"],
    country: "Francia",
    overview: "Amélie es una camarera parisina ingenua y traviesa con su propio sentido de la justicia que decide ayudar a quienes la rodean.",
    poster_path: "https://image.tmdb.org/t/p/w500/nfkB5L0n3f45uJz5x347cI3s3F.jpg",
    runtime: 122,
    awards: "4 premios César, 5 nominaciones al Óscar"
  },
  {
    id: 6479,
    title: "El laberinto del fauno",
    original_title: "El laberinto del fauno",
    year: 2006,
    directors: ["Guillermo del Toro"],
    cast: ["Ivana Baquero", "Sergi López", "Maribel Verdú", "Doug Jones"],
    genres: ["Drama", "Fantasía", "Guerra"],
    country: "España / México",
    overview: "En la España fascista de 1944, la joven hijastra de un oficial sádico del ejército escapa a un espeluznante pero cautivador mundo de fantasía.",
    poster_path: "https://image.tmdb.org/t/p/w500/9gJg3Kq2G8J2a6857L4wZ0bI434.jpg",
    runtime: 118,
    awards: "3 premios Óscar y 7 premios Goya"
  },
  {
    id: 105,
    title: "Regreso al futuro (Back to the Future)",
    original_title: "Back to the Future",
    year: 1985,
    directors: ["Robert Zemeckis"],
    cast: ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson", "Crispin Glover"],
    genres: ["Aventura", "Comedia", "Ciencia ficción"],
    country: "Estados Unidos",
    overview: "Marty McFly, un estudiante de secundaria de 17 años, es enviado accidentalmente treinta años al pasado en un DeLorean que viaja en el tiempo inventado por su amigo Doc Brown.",
    poster_path: "https://image.tmdb.org/t/p/w500/7lyBcpYB0Qt8gYvXYaEZpnWbaIP.jpg",
    runtime: 116,
    awards: "1 premio Óscar"
  },
  {
    id: 77,
    title: "Memento",
    original_title: "Memento",
    year: 2000,
    directors: ["Christopher Nolan"],
    cast: ["Guy Pearce", "Carrie-Anne Moss", "Joe Pantoliano", "Mark Boone Junior"],
    genres: ["Misterio", "Suspense"],
    country: "Estados Unidos",
    overview: "Un hombre con pérdida de memoria a corto plazo intenta localizar al asesino de su esposa utilizando un elaborado sistema de notas Polaroid y tatuajes.",
    poster_path: "https://image.tmdb.org/t/p/w500/yuNs09hvpHVU1cBTCAk9z94elNa.jpg",
    runtime: 113,
    awards: "2 nominaciones a los Óscar"
  },
  {
    id: 872585,
    title: "Oppenheimer",
    original_title: "Oppenheimer",
    year: 2023,
    directors: ["Christopher Nolan"],
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr.", "Florence Pugh"],
    genres: ["Drama", "Historia"],
    country: "Estados Unidos / Reino Unido",
    overview: "La historia del científico estadounidense J. Robert Oppenheimer y su papel en el desarrollo de la bomba atómica durante el Proyecto Manhattan.",
    poster_path: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    runtime: 180,
    awards: "7 premios Óscar incluyendo Mejor Película, Director y Actor"
  },
  {
    id: 346,
    title: "Los siete samuráis",
    original_title: "Shichinin no Samurai",
    year: 1954,
    directors: ["Akira Kurosawa"],
    cast: ["Toshirô Mifune", "Takashi Shimura", "Keiko Tsushima", "Yukiko Shimazaki"],
    genres: ["Acción", "Drama"],
    country: "Japón",
    overview: "Los agricultores de un pueblo indefenso reclaman la ayuda de siete samuráis sin amo para defenderse de los bandidos despiadados.",
    poster_path: "https://image.tmdb.org/t/p/w500/8OKm79vOmv921d7bK4U5t872J0y.jpg",
    runtime: 207,
    awards: "León de Plata en Venecia"
  },
  {
    id: 429,
    title: "El bueno, el feo y el malo",
    original_title: "Il buono, il brutto, il cattivo",
    year: 1966,
    directors: ["Sergio Leone"],
    cast: ["Clint Eastwood", "Eli Wallach", "Lee Van Cleef", "Aldo Giuffrè"],
    genres: ["Western"],
    country: "Italia / España",
    overview: "Una estafa de recompensas une a dos hombres en una alianza incómoda contra un tercer forastero en una carrera para encontrar una fortuna en oro confiscado.",
    poster_path: "https://image.tmdb.org/t/p/w500/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
    runtime: 161,
    awards: "Máximo exponente del Spaguetti Western"
  }
];
